server:
  port: 8080

#数据库连接配置
spring:
  datasource:
    mysql: # mysql配置
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: 数据库地址, 这里会根据版本不同名字不一样（有的是url）
      username: 账号
      password: 密码
    doris: # doris配置
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: 数据库地址
      username: 账号
      password: 密码
